In [1]:
import numpy as np

In [15]:
a=np.array([1,2,3,4,5],dtype='int16')
a

array([1, 2, 3, 4, 5], dtype=int16)

In [6]:
b=np.array([[1,2,3,4,5],[10,20,30,40,50]])
b

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [7]:
#Get dim size of array
b.ndim

2

In [8]:
a.ndim

1

In [12]:
#Get Shape of array
#a.shape
b.shape

(2, 5)

In [16]:
#Get Type of array
a.dtype
#b.dtype

dtype('int16')

In [18]:
#Size
a.itemsize
b.itemsize

4

In [20]:
#Totsize
a.nbytes
b.nbytes

40

In [21]:
#Get specific element
a[3]

4

In [24]:
#Get specific element
b[1,0]

10

In [29]:
#Get specific row or col
#To get col array[:,a]
#To get row array[a,:]

b[1,0]

10

In [44]:
a=([[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14]])
a

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [49]:
import numpy as np

a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
a.shape

(5, 3)

In [51]:
a.ndim

2

In [52]:
a.dtype.name

'int32'

In [53]:
a.itemsize

4

In [54]:
a.size

15

In [55]:
type(a)

numpy.ndarray

In [57]:
import numpy as np
b=np.array([1.2,3.2,4.5])
b.dtype

dtype('float64')

In [59]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [62]:
np.arange( 10, 33, 3 )

array([10, 13, 16, 19, 22, 25, 28, 31])

In [68]:
from numpy import pi
np.linspace( 0, 8, 9 )  

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [75]:
a = np.array( [20,30,40,50,60] )
b = np.arange( 6 )
b

array([0, 1, 2, 3, 4, 5])